### ISSUE TITLE
[Question] Toon 2 Support

### ISSUE THREAD

**Issue by Daandamhuis** [cyberjunky/home-assistant-toon_climate#14]
Hi! 

Does this work with the Toon 2 and does it support the Air Quality sensor that is in the [Toon 2](https://toonwiki.nl/docs/verschillen-toon1-toon2/)?

**Comment by itguy013** [comment]
Yes, it supports Toon 2 but not the Air Quality sensor. I think it a humidity sensor. :)

**Comment by cyberjunky** [comment]
@itguy013 @Daandamhuis there seems to be a special text file fetch able via http from a Toon2 containing all sensor data, I have requested a sample from someone so I can implement missing data sensors.

**Comment by DiederikRhee** [comment]
@cyberjunky Yes there is. It's in /qmf/www/tsc/sensors on my Toon2. It looke like a json file:

`{"temperature":18.7, "humidity":49.7, "tvoc":0, "eco2":405}`

**Comment by cyberjunky** [comment]
@DiederikRhee what is the URL of this file?

**Comment by DiederikRhee** [comment]
It's http://TOON_IP/tsc/sensors. For me it just returns the file itself.

See https://www.domoticaforum.eu/viewtopic.php?f=97&t=12810&p=94553&hilit=json+happ_thermstat#p94553 (last item mentioned). So it's a toon2 special.

**Comment by cyberjunky** [comment]
You can create this REST sensor to get the Toon2 values:
https://gist.github.com/cyberjunky/6eac45e94405009c54da20c6de2450fa

**Comment by cyberjunky** [comment]
Closed, solution posted.
