### ISSUE TITLE
Room temperature 

### ISSUE THREAD

**Issue by Sticker298** [cyberjunky/home-assistant-toon_climate#15]
Is it possible to put the room temperature in a badge?
![93468616-9287-49BF-BAE8-AD47891F4EAC](https://user-images.githubusercontent.com/73886509/99145140-6c495200-266c-11eb-8cfd-0538b5ccefbf.jpeg)

**Comment by rbak69** [comment]
Hi was reading through the open issues. This has nothing to do with the Toon climate component but it seems to be a more generic Home Assistant question. Nevertheless you can simply do this by creating a sensor template. I have created a quick sensor to validate and to be able to show you how it is done:

platform: template
sensors:
    toon_current_room_temperature:
        friendly_name: "Room"
        unit_of_measurement: 'degrees'
        value_template: "{{ state_attr('climate.thermostaat', 'current_temperature') }}"

If you add this as a new sensor and add that sensor as a badge it will do exactly what you requested. Please note that my Toon is called "thermostaat" hence the "climate.thermostaat". If your Toon is called differently like Toon or the default "Thermostat" you need to replace that part to correctly reflect your Toon.

![Toon temp badge](https://user-images.githubusercontent.com/10872101/104812753-aa95f580-5804-11eb-9e32-c897c9fea491.jpg)

**Comment by cyberjunky** [comment]
@Sticker298 @rbak69 I have updated the README

**Comment by cyberjunky** [comment]
Closed, solution documented.
