### ISSUE TITLE
Set measured temperature manually

### ISSUE THREAD

**Issue by abelmatser** [cyberjunky/home-assistant-toon_climate#16]
This may be the wrong place to ask, but it would be cool if we could set the measured temperature manually. This allows for a multi-room set-up in which you choose which room temperature is transmitted to Toon. This would allow Toon to work efficiently for multiple rooms, instead of only the room in which it is situated.

Do you know if the option to manually change the temperature sensor inside Toon exists?

**Comment by cyberjunky** [comment]
@abelmatser I'm not aware of that, best place to ask is the Toon forum of domoticaforum.eu
