### ISSUE TITLE
Rooted Toon and Tado

### ISSUE THREAD

**Issue by ErikSiemens** [cyberjunky/home-assistant-toon_climate#17]
Hello,

I have a Tado installed by official Integrations.

I'm also using a Rooted Toon.

In configuration.yaml I added the climate component, but in HA it is added as a sensor.

What do I have to change ?

**Comment by ErikSiemens** [comment]
> @ErikSiemens Is this (older) issue still present? Can you give some more information, like part of config and screenshot of what you see? toon_climate only generated a climate device (default name is climate.toon)

Is solved. Forgot how 😉

**Comment by cyberjunky** [comment]
;-D
