### ISSUE TITLE
No connection

### ISSUE THREAD

**Issue by Kiezelke** [cyberjunky/home-assistant-toon_climate#20]
Can anyone help me?

I have no connection anymore with my Toon 2. 
When I check the log in HA, I get following error:

Logger: custom_components.toon_climate.climate
Source: custom_components/toon_climate/climate.py:122
Integration: toon_climate (documentation)
First occurred: 11:45:42 AM (124 occurrences)
Last logged: 1:48:47 PM

Timeout error occurred while polling Toon using url: http://192.168.1.120:80/happ_thermstat?action=getThermostatInfo

**Comment by cyberjunky** [comment]
@Kiezelke Are you sure your Toon 2 is rooted (requirement) and if IP and Port (here 80) is the correct one?
Do you see json code if you use your web brower with the url above?
