### ISSUE TITLE
Eco2 toon2

### ISSUE THREAD

**Issue by phoenix-blue** [cyberjunky/home-assistant-toon_climate#24]
Hi,

I see in the HA info that the Eco2 variable is not defined (yet):

`toon2_eco2:
        friendly_name: "ECO2"
        value_template: '{{ states.sensor.toon2_airsensors.attributes["eco2"] }}'
        unit_of_measurement: "?" `

I have check it here with a standalone CO2 sensor because I think it's an Co2 value in "ppm". 
Is that possible?

**Comment by cyberjunky** [comment]
@phoenix-blue can you check latest version of README, is this more correct/what you mean?

**Comment by phoenix-blue** [comment]
Hi,

Yep, looks good like this.
Thanks.
