### ISSUE TITLE
Toon boiler in en out temp unknown 

### ISSUE THREAD

**Issue by Dutchy-79** [cyberjunky/home-assistant-toon_climate#31]
Sinds 2 dagen geeft HA aan dat de Toon boiler in en out temp onbekend is. Nu zie ik hem op de Toon ook la Nan staan dus zeer zeker zit het niet in deze plugin maar wellicht heb je een idee wat het kan zijn?

**Comment by cyberjunky** [comment]
Die boiler gegevens worden niet meer altijd getoond, nieuwste versies Toon software niet meer meen ik.
