### ISSUE TITLE
Warning on 2021.12.0b0: Entity climate.woonkamer (..) implements device_state_attributes

### ISSUE THREAD

**Issue by hmmbob** [cyberjunky/home-assistant-toon_climate#35]
After upgrading to 2021.12.b0 I'm seeing this warning in my logs:

```py
2021-12-04 10:29:36 WARNING (MainThread) [homeassistant.helpers.entity] Entity climate.woonkamer (<class 'custom_components.toon_climate.climate.ThermostatDevice'>) implements device_state_attributes. Please report it to the custom component author.
```

Requested more info in the #beta channel on Discord, got this info:

![image](https://user-images.githubusercontent.com/33529490/144704855-b4277b58-69e2-4dd7-b655-13b03a26a453.png)

**Comment by rbak69** [comment]
@hmmbob thanks for letting us know. I will change it in the code in order to get rid of the warning.

**Comment by hmmbob** [comment]
Thanks. Don't know about backwards compatibility....

**Comment by rbak69** [comment]
@hmmbob just checked on core-2021.11.5 and it works just fine

**Comment by hmmbob** [comment]
Seeing another warning in debug mode:

```
/config/custom_components/toon_climate/climate.py:198: DeprecationWarning: with timeout() is deprecated, use async with timeout() instead
  with async_timeout.timeout(5):
```
