### ISSUE TITLE
foutmeldingen  timeout occured when polling Toon Thermostat

### ISSUE THREAD

**Issue by DoerakkerHA** [cyberjunky/home-assistant-toon_climate#43]
This error originated from a custom integration.

Logger: custom_components.toon_climate.climate
Source: custom_components/toon_climate/climate.py:240
Integration: toon_climate (documentation, issues)
First occurred: August 8, 2023 at 05:57:11 (191 occurrences)
Last logged: 07:29:11

Timeout error occurred while polling Toon Thermostat using url: http://192.168.178.10:80/happ_thermstat?action=getThermostatInfo
Cannot poll Toon Thermostat using url: http://192.168.178.10:80/happ_thermstat?action=getThermostatInfo

Yes, I receive data when submitting url via browser: 
{"result":"ok", "currentTemp":"2189", "currentSetpoint":"1400", "currentInternalBoilerSetpoint":"6", "programState":"0", "activeState":"2", "nextProgram":"-1", "nextState":"-1", "nextTime":"0","nextSetpoint":"0","randomConfigId":"1804289383","errorFound":"255","connection":"0","burnerInfo":"0","otCommError":"0","currentModulationLevel":"0"}

please advise

**Comment by DoerakkerHA** [comment]
Hello is there any news regarding this recurring issue ?

**Comment by cyberjunky** [comment]
Could be simply, due to temporary bad Wifi conncection. Toon uses 2.4Ghz band which is full sometimes, or disturbed by neighbor networks, I have a few error like this in the night, nothing the integration can do about

**Comment by cyberjunky** [comment]
Closing because stale ticket
