### ISSUE TITLE
Toon and HA both act as thermostat

### ISSUE THREAD

**Issue by DennisDeKoster** [cyberjunky/home-assistant-toon_climate#46]
I have my Toon for a long time and I know that its thermostat used to "learn the house". So it knows how long it takes to heat the house to the set temperature. 

I have programmed my Toon with Sleep, Away, Home and Comfort at set times during the week. The Toon thermostat wants to have the house at the desired temperature and starts heating early according the learned information. The HA climate entity knows the set temperature and concludes it is either not necessary to heat or decides to heat when not necessary, so they collide. Also I noticed that HA switches between Idle and Heating within a single minute, which not helps to maintain temperature and frequent switching could possibly be bad for the heater as well (my heater is not OpenTherm).

I hope that you know what I mean. I can explain myself further in Nederlands if you desire.

Is there a way to let Toon do its thing and HA just watches, but is able to manually set a temperature or change modes?

**Comment by rbak69** [comment]
Hi @DennisDeKoster,

Reading your message I get the impression that you think the HA climate entity is actively steering the heater. But that is not the case. The HA climate entity is simply presenting the status information it receives from the Toon through this custom integration.

The HA climate entity does however allow you to control the Toon (if you wish) using automations that change the work mode or change the set point. For example, in my home I switch the Toon automatically to Manual mode and a low setpoint when presence detection determines none of my family members are at home. As soon as presence detection determines that any of my family members are back at home it will automatically switch the Toon back to Auto mode (the heating program in the Toon).

What you seem to describe is the discrepancy between the status you see on the Toon and the status you see in the HA climate entity. You need to understand that the Toon integration is polling the status of the Toon at regular intervals and the result is shown in the HA climate entity. So it can well be that the Toon started heating already while the HA climate entity is still showing as idle until the next polling cycle receives the new update. The other way round might also be true.

But as said the HA climate instance by itself is not actively steering the Toon and as such this can never colide. So it does indeed  already allow the Toon to "do its thing" ;-)

I hope that answers your question and takes away your concern.

Kind regards,
Rene

**Comment by DennisDeKoster** [comment]
Hi Rene, 

thank you for clarifying! This makes sense,  but it made me doubt.
