### ISSUE TITLE
Detected I/O inside the event loop. 

### ISSUE THREAD

**Issue by Edwintenhaaf** [cyberjunky/home-assistant-toon_climate#5]
As requested by Homeassistant:

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for toon_smartmeter doing I/O at custom_components/toon_smartmeter/sensor.py, line 126: self._data =requests.get(self._build_url(), timeout=10).json()

**Comment by cyberjunky** [comment]
This issue was raised in toon_climate repo, but log shows toon_smartmeter code.
Can you update to latest version, it was fixed for smartmeter too.
If you use HACS, it's simple. Otherwise download from github repo.

**Comment by Edwintenhaaf** [comment]
I'm sorry, I saw in the readme to use HACS I just did and updated!
